# fly.toml app configuration file generated for avse-hasura-prod on 2024-01-02T16:23:07+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "avse-hasura-prod"
primary_region = "dfw"

[build]
  image = "hasura/graphql-engine:v2.25.1-ce"

[env]
  ADMIN_KEY = "admin"
  HASURA_GRAPHQL_ADMIN_SECRET = "admin"
  HASURA_GRAPHQL_DATABASE_URL = "postgresql://postgres:irrNA2PCVA9AQAbz@db.oblchcgkguvwsgylnfvs.supabase.co:5432/postgres"
  HASURA_GRAPHQL_DEV_MODE = "true"
  HASURA_GRAPHQL_ENABLE_CONSOLE = "true"
  HASURA_GRAPHQL_JWT_SECRET = "{\"key\":\"aiUi4yW8skdMBuGal4/4Pq8lavBskJh8gOP79KiSHZh/Sboe1zTI5ccHNAa0AlgKujJmE6H6IJxtLJH7ZW0Xug==\",\"type\":\"HS256\",\"claims_namespace_path\":\"$.app_metadata.hasura\",\"allowed_skew\":86400}"
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE = "public"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  [http_service.concurrency]
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = "1m0s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/healthz"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
